log_format timed_combined '$remote_addr - $remote_user [$time_local] '
                         '"$request" $status $body_bytes_sent '
                         '"$http_referer" "$http_user_agent" "$gzip_ratio"'
                         'rt=$request_time uct=$upstream_connect_time '
                         'uht=$upstream_header_time urt=$upstream_response_time';

upstream django {
    server 127.0.0.1:8000;
}

upstream node {
    server 127.0.0.1:3000;
}

map $http_x_forwarded_proto $bolls_forwarded_proto {
    default $http_x_forwarded_proto;
    ''      $scheme;
}

server {
    listen 80;

    access_log /var/log/nginx/access.log timed_combined;

    client_body_buffer_size 32k;
    client_max_body_size 5m;

    location ~ ^(/admin/|/api|/accounts/*|/login/*|/signup/|/get-*|/history/|/save-bookmarks/|/save-freehand-highlights/|/delete-bookmarks/|/edit-account/|/delete-my-account/|/user-logged/|/download-notes/|/import-notes/|/save-compare-translations/|/search/|/find/|/v2/|/dictionary-definition/|/complete/*|/disconnect/*) {
        proxy_pass http://django;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $bolls_forwarded_proto;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static/bolls/app/views/ {
        alias /app/imba/src/data/;
    }

    location /static/ {
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css text/xml text/html text/javascript application/javascript application/x-javascript application/xml application/json;
        alias /home/bolls/web/static/;

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Accept,Origin' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
    }

    location / {
        proxy_pass http://node;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $bolls_forwarded_proto;
        proxy_set_header Host $host;
        proxy_redirect off;

        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css text/xml text/html text/javascript application/javascript application/x-javascript application/xml application/json;

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Accept,Origin' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
    }

    location /favicon.ico {
        alias /home/bolls/web/static/favicon.ico;
    }

    location ~ ^/(sw\.js|service\.worker\.js|service-worker\.js)$ {
        alias /app/imba/public/sw/service.worker.js;
    }
}
