[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:postgresql]
command=/usr/local/bin/run-postgres.sh
user=postgres
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/log/supervisor/postgresql.log
stderr_logfile=/var/log/supervisor/postgresql.err.log

[program:django]
command=/usr/local/bin/run-django.sh
user=bollsuser
autostart=true
autorestart=true
priority=20
startsecs=5
stdout_logfile=/var/log/supervisor/django.log
stderr_logfile=/var/log/supervisor/django.err.log

[program:imba]
command=/usr/local/bin/run-imba.sh
autostart=true
autorestart=true
priority=20
startsecs=5
stdout_logfile=/var/log/supervisor/imba.log
stderr_logfile=/var/log/supervisor/imba.err.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=30
startsecs=2
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx.err.log
