# Generated by Django 6.0 on 2026-01-31 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0013_commentary_bolls_comme_transla_851084_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreehandHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=120)),
                ('book', models.PositiveSmallIntegerField()),
                ('chapter', models.PositiveSmallIntegerField()),
                ('highlights', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'translation', 'book', 'chapter'], name='bolls_freeh_user_id_3e54a6_idx')],
            },
        ),
    ]
