# Generated by Django 6.0

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bolls", "0014_freehandhighlight"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerseNoteLink",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("block_id", models.CharField(max_length=64)),
                ("translation", models.CharField(max_length=120)),
                ("book", models.PositiveSmallIntegerField()),
                ("chapter", models.PositiveSmallIntegerField()),
                ("start_verse", models.PositiveSmallIntegerField()),
                ("end_verse", models.PositiveSmallIntegerField()),
                ("note_path", models.TextField()),
                ("note_name", models.CharField(blank=True, default="", max_length=255)),
                ("vault", models.CharField(blank=True, default="", max_length=255)),
                ("date", models.BigIntegerField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="versenotelink",
            constraint=models.UniqueConstraint(fields=("user", "block_id"), name="uniq_user_verse_note_link"),
        ),
        migrations.AddIndex(
            model_name="versenotelink",
            index=models.Index(fields=["user", "translation", "book", "chapter"], name="bolls_verse_user_id_note_idx"),
        ),
        migrations.AddIndex(
            model_name="versenotelink",
            index=models.Index(fields=["user", "block_id"], name="bolls_verse_user_block_idx"),
        ),
    ]
