# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bolls", "0015_versenotelink"),
    ]

    operations = [
        migrations.AddField(
            model_name="versenotelink",
            name="broken",
            field=models.BooleanField(default=False),
        ),
    ]
