/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BibleViewerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  bibleAppUrl: "https://bolls.familybravo.com"
};
var BibleViewerPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(
      "bible-viewer",
      (leaf) => this.bibleView = new BibleView(leaf, this)
    );
    this.addCommand({
      id: "open-bible-viewer",
      name: "Open Bible Viewer",
      callback: () => {
        this.activateView();
      }
    });
    this.addRibbonIcon("book-open", "Open Bible Viewer", () => {
      this.activateView();
    });
    this.addSettingTab(new BibleViewerSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.activateView();
    });
  }
  onunload() {
    this.app.workspace.detachLeavesOfType("bible-viewer");
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
    if (this.settings.bibleAppUrl === "http://localhost:8080" || this.settings.bibleAppUrl === "http://127.0.0.1:8080") {
      this.settings.bibleAppUrl = DEFAULT_SETTINGS.bibleAppUrl;
      await this.saveSettings();
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType("bible-viewer");
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      await leaf.setViewState({
        type: "bible-viewer",
        active: true
      });
    }
    workspace.revealLeaf(leaf);
  }
};
var BibleView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.lastMarkdownLeaf = null;
    this.plugin = plugin;
    this.messageHandler = this.handleMessage.bind(this);
  }
  rememberMarkdownLeaf(leaf) {
    if ((leaf == null ? void 0 : leaf.view) instanceof import_obsidian.MarkdownView) {
      this.lastMarkdownLeaf = leaf;
    }
  }
  getMarkdownViewForInsert() {
    var _a;
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (activeView) {
      this.lastMarkdownLeaf = activeView.leaf;
      return activeView;
    }
    if (((_a = this.lastMarkdownLeaf) == null ? void 0 : _a.view) instanceof import_obsidian.MarkdownView) {
      return this.lastMarkdownLeaf.view;
    }
    const markdownLeaves = this.app.workspace.getLeavesOfType("markdown");
    for (const leaf of markdownLeaves) {
      if (leaf.view instanceof import_obsidian.MarkdownView) {
        this.lastMarkdownLeaf = leaf;
        return leaf.view;
      }
    }
    return null;
  }
  getViewType() {
    return "bible-viewer";
  }
  getDisplayText() {
    return "Bible Viewer";
  }
  getIcon() {
    return "book-open";
  }
  async onOpen() {
    this.rememberMarkdownLeaf(this.app.workspace.activeLeaf);
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        this.rememberMarkdownLeaf(leaf);
      })
    );
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("bible-viewer-container");
    const timestamp = Date.now();
    const random = Math.random().toString(36).substring(7);
    const cacheBuster = `?v=${timestamp}&_nocache=1&_refresh=${random}&_t=${timestamp}&_r=${random}&sw=bypass&_cb=${timestamp}${random}`;
    this.iframe = container.createEl("iframe", {
      cls: "bible-viewer-iframe",
      attr: {
        sandbox: "allow-same-origin allow-scripts allow-forms allow-popups"
      }
    });
    setTimeout(() => {
      if (this.iframe) {
        this.iframe.src = this.plugin.settings.bibleAppUrl + cacheBuster;
        console.log("Bible Viewer: Iframe src set with cache-buster:", cacheBuster);
        let cacheCleared = false;
        this.iframe.onload = () => {
          if (cacheCleared) {
            return;
          }
          cacheCleared = true;
          setTimeout(() => {
            var _a;
            try {
              const iframeWindow = (_a = this.iframe) == null ? void 0 : _a.contentWindow;
              if (iframeWindow) {
                iframeWindow.postMessage({ type: "clear-cache", force: true, timestamp: Date.now() }, "*");
                console.log("Bible Viewer: Sent clear-cache message to iframe");
                iframeWindow.postMessage({ type: "unregister-sw", force: true, timestamp: Date.now() }, "*");
              }
            } catch (e) {
              console.log("Bible Viewer: Could not access iframe window (expected if cross-origin)");
            }
          }, 500);
        };
      }
    }, 10);
    window.addEventListener("message", this.messageHandler);
    console.log("Bible Viewer: Message listener added, iframe loaded with cache-buster:", cacheBuster);
  }
  async onload() {
    if (this.iframe) {
      this.refreshIframe();
    }
  }
  async onClose() {
    if (this.messageHandler) {
      window.removeEventListener("message", this.messageHandler);
      console.log("Bible Viewer: Message listener removed");
    }
  }
  refreshIframe() {
    if (this.iframe) {
      const timestamp = Date.now();
      const random = Math.random().toString(36).substring(7);
      const cacheBuster = `?v=${timestamp}&_nocache=1&_refresh=${random}&_t=${timestamp}&_r=${random}&sw=bypass&_force=1&_cb=${timestamp}${random}`;
      const oldIframe = this.iframe;
      const container = oldIframe.parentElement;
      oldIframe.remove();
      this.iframe = container.createEl("iframe", {
        cls: "bible-viewer-iframe",
        attr: {
          sandbox: "allow-same-origin allow-scripts allow-forms allow-popups"
        }
      });
      setTimeout(() => {
        if (this.iframe) {
          this.iframe.src = this.plugin.settings.bibleAppUrl + cacheBuster;
          console.log("Bible Viewer: Iframe recreated with cache-buster:", cacheBuster);
          let cacheCleared = false;
          this.iframe.onload = () => {
            if (cacheCleared) {
              return;
            }
            cacheCleared = true;
            setTimeout(() => {
              var _a;
              try {
                const iframeWindow = (_a = this.iframe) == null ? void 0 : _a.contentWindow;
                if (iframeWindow) {
                  iframeWindow.postMessage({ type: "clear-cache", force: true, timestamp: Date.now() }, "*");
                  console.log("Bible Viewer: Sent clear-cache message to iframe after refresh");
                  iframeWindow.postMessage({ type: "unregister-sw", force: true, timestamp: Date.now() }, "*");
                }
              } catch (e) {
                console.log("Bible Viewer: Could not access iframe window (expected if cross-origin)");
              }
            }, 500);
          };
        }
      }, 10);
    }
  }
  isAllowedMessageOrigin(origin) {
    if (origin === "null" || origin === window.location.origin) {
      return true;
    }
    if (origin.includes("localhost") || origin.includes("127.0.0.1")) {
      return true;
    }
    try {
      return new URL(origin).origin === new URL(this.plugin.settings.bibleAppUrl).origin;
    } catch (e) {
      return false;
    }
  }
  handleMessage(event) {
    var _a;
    console.log("Bible Viewer: Received message", {
      origin: event.origin,
      data: event.data,
      dataType: typeof event.data,
      dataKeys: event.data ? Object.keys(event.data) : [],
      source: event.source
    });
    const fromIframe = event.source === ((_a = this.iframe) == null ? void 0 : _a.contentWindow);
    if (!this.isAllowedMessageOrigin(event.origin) && !fromIframe) {
      console.log("Bible Viewer: Rejected message from origin", event.origin);
      return;
    }
    if (event.data && event.data.type === "bible-verse-selection") {
      console.log("Bible Viewer: Processing verse selection", event.data);
      console.log("Bible Viewer: Translation in data:", event.data.translation);
      this.copyVersesToNote(event.data);
    } else if (event.data && event.data.type === "bible-commentary-selection") {
      console.log("Bible Viewer: Processing commentary selection", event.data);
      this.copyCommentaryToNote(event.data);
    } else {
      console.log("Bible Viewer: Message type mismatch or no data", event.data);
    }
  }
  copyVersesToNote(data) {
    const verses = data.verses;
    console.log("Bible Viewer: copyVersesToNote called with", data);
    console.log("Bible Viewer: Data keys:", Object.keys(data));
    console.log("Bible Viewer: Translation field:", data.translation);
    const activeView = this.getMarkdownViewForInsert();
    if (!activeView) {
      console.log("Bible Viewer: No active markdown view");
      new import_obsidian.Notice("No active note to copy verses to.");
      return;
    }
    console.log("Bible Viewer: Active view found", activeView);
    const firstVerse = verses[0];
    const lastVerse = verses[verses.length - 1];
    let referenceText;
    if (verses.length === 1) {
      referenceText = firstVerse.reference;
    } else {
      if (firstVerse.verse === lastVerse.verse) {
        referenceText = firstVerse.reference;
      } else {
        referenceText = `${firstVerse.reference}-${lastVerse.verse}`;
      }
    }
    console.log("Bible Viewer: Full data object received:", JSON.stringify(data, null, 2));
    console.log("Bible Viewer: data.translation value:", data.translation);
    console.log("Bible Viewer: All data keys:", Object.keys(data || {}));
    const translationCode = (data == null ? void 0 : data.translation) || "BBE";
    console.log("Bible Viewer: Using translation code:", translationCode);
    const bookId = data.bookId || 1;
    const chapter = data.chapter || 1;
    let verseRange;
    if (verses.length === 1) {
      verseRange = `${firstVerse.verse}`;
    } else {
      verseRange = `${firstVerse.verse}-${lastVerse.verse}`;
    }
    const url = `${this.plugin.settings.bibleAppUrl}/${translationCode}/${bookId}/${chapter}/${verseRange}`;
    const calloutHeader = `> [!bible] [${referenceText} - ${translationCode}](${url})`;
    const verseTexts = verses.map((v) => `> ${v.verse}. ${v.text}`).join("\n");
    const formattedText = `${calloutHeader}
${verseTexts}

`;
    const editor = activeView.editor;
    const cursor = editor.getCursor();
    editor.replaceRange(formattedText, cursor);
    new import_obsidian.Notice(`Copied ${verses.length} verse${verses.length > 1 ? "s" : ""} to note`);
  }
  copyCommentaryToNote(data) {
    var _a, _b;
    const sections = data.sections || [];
    if (sections.length === 0) {
      new import_obsidian.Notice("No commentary to copy.");
      return;
    }
    const activeView = this.getMarkdownViewForInsert();
    if (!activeView) {
      new import_obsidian.Notice("No active note to copy commentary to.");
      return;
    }
    const translationCode = (data == null ? void 0 : data.translation) || "BBE";
    const bookId = data.bookId || 1;
    const chapter = data.chapter || 1;
    const verse = ((_a = sections[0]) == null ? void 0 : _a.verse) || 1;
    const title = data.commentaryTitle || "Comentario B\xEDblico Adventista";
    const reference = data.reference || ((_b = sections[0]) == null ? void 0 : _b.reference) || `${data.book || "Genesis"} ${chapter}:${verse}`;
    const url = `${this.plugin.settings.bibleAppUrl}/${translationCode}/${bookId}/${chapter}/${verse}`;
    const body = sections.map((section) => section.text.trim()).filter((text) => text.length > 0).map(
      (text) => text.split(/\n+/).filter((line) => line.trim().length > 0).map((line) => `> ${line.trim()}`).join("\n")
    ).join("\n>\n");
    const calloutHeader = `> [!note] [${title}](${url})`;
    const subtitleLine = `> ${reference}`;
    const formattedText = `${calloutHeader}
${subtitleLine}
${body}

`;
    const editor = activeView.editor;
    const cursor = editor.getCursor();
    editor.replaceRange(formattedText, cursor);
    new import_obsidian.Notice(`Copied commentary to note`);
  }
};
var BibleViewerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Bible Viewer Settings" });
    new import_obsidian.Setting(containerEl).setName("Bible App URL").setDesc("URL of the Bible app (default: https://bolls.familybravo.com)").addText(
      (text) => text.setPlaceholder("https://bolls.familybravo.com").setValue(this.plugin.settings.bibleAppUrl).onChange(async (value) => {
        this.plugin.settings.bibleAppUrl = value;
        await this.plugin.saveSettings();
        if (this.plugin.bibleView) {
          const cacheBuster = `?v=${Date.now()}&_nocache=1&_refresh=${Math.random()}`;
          this.plugin.bibleView.refreshIframe();
        }
      })
    );
  }
};
