/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BibleViewerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  bibleAppUrl: "http://localhost:8080"
};
var BibleViewerPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(
      "bible-viewer",
      (leaf) => this.bibleView = new BibleView(leaf, this)
    );
    this.addCommand({
      id: "open-bible-viewer",
      name: "Open Bible Viewer",
      callback: () => {
        this.activateView();
      }
    });
    this.addRibbonIcon("book-open", "Open Bible Viewer", () => {
      this.activateView();
    });
    this.addSettingTab(new BibleViewerSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.activateView();
    });
  }
  onunload() {
    this.app.workspace.detachLeavesOfType("bible-viewer");
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType("bible-viewer");
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      await leaf.setViewState({
        type: "bible-viewer",
        active: true
      });
    }
    workspace.revealLeaf(leaf);
  }
};
var BibleView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.listenerRegistered = false;
    this.lastMessageFingerprint = "";
    this.lastMessageAt = 0;
    this.plugin = plugin;
    this.messageHandler = this.handleMessage.bind(this);
  }
  getViewType() {
    return "bible-viewer";
  }
  getDisplayText() {
    return "Bible Viewer";
  }
  getIcon() {
    return "book-open";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("bible-viewer-container");
    const timestamp = Date.now();
    const random = Math.random().toString(36).substring(7);
    const cacheBuster = `?v=${timestamp}&_nocache=1&_refresh=${random}&_t=${timestamp}&_r=${random}&sw=bypass&_cb=${timestamp}${random}`;
    this.iframe = container.createEl("iframe", {
      cls: "bible-viewer-iframe",
      attr: {
        sandbox: "allow-same-origin allow-scripts allow-forms allow-popups"
      }
    });
    setTimeout(() => {
      if (this.iframe) {
        this.iframe.src = this.plugin.settings.bibleAppUrl + cacheBuster;
        console.log("Bible Viewer: Iframe src set with cache-buster:", cacheBuster);
        let cacheCleared = false;
        this.iframe.onload = () => {
          if (cacheCleared) {
            return;
          }
          cacheCleared = true;
          setTimeout(() => {
            var _a;
            try {
              const iframeWindow = (_a = this.iframe) == null ? void 0 : _a.contentWindow;
              if (iframeWindow) {
                iframeWindow.postMessage({ type: "clear-cache", force: true, timestamp: Date.now() }, "*");
                console.log("Bible Viewer: Sent clear-cache message to iframe");
                iframeWindow.postMessage({ type: "unregister-sw", force: true, timestamp: Date.now() }, "*");
              }
            } catch (e) {
              console.log("Bible Viewer: Could not access iframe window (expected if cross-origin)");
            }
          }, 500);
        };
      }
    }, 10);
    if (!this.listenerRegistered) {
      window.addEventListener("message", this.messageHandler);
      this.listenerRegistered = true;
    }
    console.log("Bible Viewer: Message listener added, iframe loaded with cache-buster:", cacheBuster);
  }
  async onload() {
    if (this.iframe) {
      this.refreshIframe();
    }
  }
  async onClose() {
    if (this.messageHandler && this.listenerRegistered) {
      window.removeEventListener("message", this.messageHandler);
      this.listenerRegistered = false;
      console.log("Bible Viewer: Message listener removed");
    }
  }
  refreshIframe() {
    if (this.iframe) {
      const timestamp = Date.now();
      const random = Math.random().toString(36).substring(7);
      const cacheBuster = `?v=${timestamp}&_nocache=1&_refresh=${random}&_t=${timestamp}&_r=${random}&sw=bypass&_force=1&_cb=${timestamp}${random}`;
      const oldIframe = this.iframe;
      const container = oldIframe.parentElement;
      oldIframe.remove();
      this.iframe = container.createEl("iframe", {
        cls: "bible-viewer-iframe",
        attr: {
          sandbox: "allow-same-origin allow-scripts allow-forms allow-popups"
        }
      });
      setTimeout(() => {
        if (this.iframe) {
          this.iframe.src = this.plugin.settings.bibleAppUrl + cacheBuster;
          console.log("Bible Viewer: Iframe recreated with cache-buster:", cacheBuster);
          let cacheCleared = false;
          this.iframe.onload = () => {
            if (cacheCleared) {
              return;
            }
            cacheCleared = true;
            setTimeout(() => {
              var _a;
              try {
                const iframeWindow = (_a = this.iframe) == null ? void 0 : _a.contentWindow;
                if (iframeWindow) {
                  iframeWindow.postMessage({ type: "clear-cache", force: true, timestamp: Date.now() }, "*");
                  console.log("Bible Viewer: Sent clear-cache message to iframe after refresh");
                  iframeWindow.postMessage({ type: "unregister-sw", force: true, timestamp: Date.now() }, "*");
                }
              } catch (e) {
                console.log("Bible Viewer: Could not access iframe window (expected if cross-origin)");
              }
            }, 500);
          };
        }
      }, 10);
    }
  }
  handleMessage(event) {
    var _a, _b;
    let data = event.data;
    if (typeof data === "string") {
      try {
        data = JSON.parse(data);
      } catch (e) {
        return;
      }
    }
    console.log("Bible Viewer: Received message", {
      origin: event.origin,
      data,
      dataType: typeof data,
      dataKeys: data ? Object.keys(data) : [],
      source: event.source
    });
    const isLocalhost = event.origin.includes("localhost") || event.origin.includes("127.0.0.1") || event.origin === "null" || // Some browsers use "null" for same-origin
    event.source === ((_a = this.iframe) == null ? void 0 : _a.contentWindow);
    if (!isLocalhost) {
      console.log("Bible Viewer: Rejected message from origin", event.origin);
      return;
    }
    if (data && data.type === "bible-verse-selection") {
      const fingerprint = JSON.stringify({
        type: data.type,
        translation: data.translation,
        book: data.book,
        chapter: data.chapter,
        verses: (_b = data.verses) == null ? void 0 : _b.map((v) => ({
          reference: v.reference,
          verse: v.verse,
          text: v.text
        }))
      });
      const now = Date.now();
      if (fingerprint === this.lastMessageFingerprint && now - this.lastMessageAt < 1500) {
        console.log("Bible Viewer: Dropped duplicate verse-selection message");
        return;
      }
      this.lastMessageFingerprint = fingerprint;
      this.lastMessageAt = now;
      console.log("Bible Viewer: Processing verse selection", data);
      console.log("Bible Viewer: Translation in data:", data.translation);
      this.copyVersesToNote(data);
    } else {
      console.log("Bible Viewer: Message type mismatch or no data", data);
    }
  }
  copyVersesToNote(data) {
    const verses = data.verses;
    console.log("Bible Viewer: copyVersesToNote called with", data);
    console.log("Bible Viewer: Data keys:", Object.keys(data));
    console.log("Bible Viewer: Translation field:", data.translation);
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView) {
      console.log("Bible Viewer: No active markdown view");
      new import_obsidian.Notice("No active note to copy verses to.");
      return;
    }
    console.log("Bible Viewer: Active view found", activeView);
    const firstVerse = verses[0];
    const lastVerse = verses[verses.length - 1];
    let referenceText;
    if (verses.length === 1) {
      referenceText = firstVerse.reference;
    } else {
      if (firstVerse.verse === lastVerse.verse) {
        referenceText = firstVerse.reference;
      } else {
        referenceText = `${firstVerse.reference}-${lastVerse.verse}`;
      }
    }
    console.log("Bible Viewer: Full data object received:", JSON.stringify(data, null, 2));
    console.log("Bible Viewer: data.translation value:", data.translation);
    console.log("Bible Viewer: All data keys:", Object.keys(data || {}));
    const translationCode = (data == null ? void 0 : data.translation) || "BBE";
    console.log("Bible Viewer: Using translation code:", translationCode);
    const bookId = data.bookId || 1;
    const chapter = data.chapter || 1;
    let verseRange;
    if (verses.length === 1) {
      verseRange = `${firstVerse.verse}`;
    } else {
      verseRange = `${firstVerse.verse}-${lastVerse.verse}`;
    }
    const url = `${this.plugin.settings.bibleAppUrl}/${translationCode}/${bookId}/${chapter}/${verseRange}`;
    const calloutHeader = `> [!bible] [${referenceText} - ${translationCode}](${url})`;
    const verseTexts = verses.map((v) => `> ${v.verse}. ${v.text}`).join("\n");
    const formattedText = `${calloutHeader}
${verseTexts}

`;
    const editor = activeView.editor;
    const cursor = editor.getCursor();
    editor.replaceRange(formattedText, cursor);
    new import_obsidian.Notice(`Copied ${verses.length} verse${verses.length > 1 ? "s" : ""} to note`);
  }
};
var BibleViewerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Bible Viewer Settings" });
    new import_obsidian.Setting(containerEl).setName("Bible App URL").setDesc("URL of the Bible app (default: http://localhost:8080)").addText(
      (text) => text.setPlaceholder("http://localhost:8080").setValue(this.plugin.settings.bibleAppUrl).onChange(async (value) => {
        this.plugin.settings.bibleAppUrl = value;
        await this.plugin.saveSettings();
        if (this.plugin.bibleView) {
          const cacheBuster = `?v=${Date.now()}&_nocache=1&_refresh=${Math.random()}`;
          this.plugin.bibleView.refreshIframe();
        }
      })
    );
  }
};
