http:
  routers:
    nginx:
      rule: "Host(`bolls.local`) || Host(`localhost`)"
      service: "nginx"
      entryPoints:
        - http
  services:
    nginx:
      loadBalancer:
        servers:
          - url: "http://nginx:80"
